version: '3.8'
services:
  db:
    image: postgres:12
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./infra/.env
  backend:
    # image: konstantin05/foodgram_backend:latest
    build: 
      context: .
      dockerfile: ./docker/backend/Dockerfile
    expose:
      - 8000
    restart: always
    volumes:
      - ./backend:/app # локальная папка стала папкой контейнера. перезагрузка контейнера после сохранения кода
      - static_value:/app/backend_static/
      - media_value:/app/backend_media/
    env_file:
      - ./infra/.env
    depends_on:
      - db
  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./infra/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs/redoc.html:/usr/share/nginx/html/api/docs/redoc.html
      - ./docs/openapi-schema.yml:/usr/share/nginx/html/api/docs/openapi-schema.yml
      - static_value:/app/backend_static/
      - media_value:/app/backend_media/
    restart: always
    depends_on:
      - frontend
  frontend:
      image: konstantin05/foodgram_frontend:latest
      volumes:
        - ./frontend/:/app/result_build/
volumes:
  static_value:
  media_value:
  postgres_data:
