version: '3.8'

# имена и описания контейнеров, которые должны быть развёрнуты
services:
  backend:
    image: konstantin05/foodgram_backend:latest
    expose:
      - 8000
    restart: always
    volumes:
      - static_value:/app/backend_static/
      - media_value:/app/backend_media/
    env_file:
      - ./.env

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_value:/app/backend_static/
      - media_value:/app/backend_media/
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs:/usr/share/nginx/html/api/docs/
    restart: always
    depends_on:
      - frontend

  frontend:
    image: konstantin05/foodgram_frontend:latest
    volumes:
      - ../frontend/:/app/result_build/

volumes:
  static_value:
  media_value:
