# Generated by Django 4.0.6 on 2022-10-10 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_token_alter_user_options_alter_user_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
    ]
